import { Container } from 'react-bootstrap';
import React from 'react';

const About = () => {
    return (<>
        <Container>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus molestias provident assumenda quae aut eos, vero, praesentium corporis eveniet ab hic fugiat. Quod rerum delectus sit asperiores alias cumque assumenda nulla harum eaque aliquam saepe totam cupiditate placeat aspernatur eum error, beatae quam ipsa neque! Eligendi nisi dignissimos eum architecto est sint et expedita? Ea laboriosam alias vitae recusandae quis expedita. Sit ipsam, deserunt aliquam temporibus beatae commodi incidunt cum exercitationem facere illo inventore cupiditate rem maiores quod qui quam earum eveniet saepe quas, ipsum, amet fuga itaque dicta. At perspiciatis quos debitis quae in ab provident culpa accusamus voluptas eum voluptates dignissimos aut qui doloribus, aspernatur eligendi odio officia esse officiis? Ab aut quibusdam error, consequuntur rem velit earum alias quae quos ullam ea. Consequatur quidem sed enim porro assumenda, voluptate debitis fuga, itaque perspiciatis suscipit, aliquid dolores officiis corrupti praesentium veniam voluptates nihil! Dolorem eligendi doloribus nam libero dolor animi architecto qui recusandae, minus, nisi repellat ipsam praesentium eveniet omnis? Dolore ab voluptates pariatur magnam, impedit laudantium deleniti tempore distinctio atque sit consectetur vel. Cumque, commodi tempore harum maiores ipsam vero eaque rerum earum ipsum? Voluptatibus facilis ab modi sunt debitis placeat, vel error reprehenderit, laboriosam iusto illum maxime libero nisi ut corporis quae saepe iure dolorum recusandae, mollitia labore soluta dolorem deleniti laborum? Dicta sint illum, commodi, quibusdam ullam in autem ea fugiat natus voluptas perspiciatis facilis animi aspernatur nam numquam reiciendis libero. Sunt non error voluptatum, perspiciatis aspernatur facilis, harum neque distinctio corrupti pariatur vero, expedita nam blanditiis qui ipsa voluptatibus doloribus eum! In sit, dolorum reprehenderit mollitia ab magnam voluptatum ipsa tenetur fugit, a molestiae, nemo explicabo? Dignissimos facilis, ea laboriosam eum saepe dolore tempora maxime. Voluptas amet eligendi natus ex aliquam? Animi ad error vitae nihil distinctio, culpa commodi ratione quam fugit inventore qui dolores cum tempore eaque, expedita quas laborum. Perferendis maxime illo, quaerat amet recusandae quia ut tenetur qui nam perspiciatis a quo harum accusamus. Dignissimos, delectus sequi. Qui, laudantium nemo praesentium tempora nulla cumque asperiores fugit temporibus perspiciatis, a magnam, id vero. Excepturi, debitis nihil. Laboriosam laudantium laborum nostrum praesentium sint incidunt nobis quo facilis delectus accusantium, obcaecati consequatur architecto a vero harum exercitationem unde repellat iusto aspernatur libero quis minima fugiat reiciendis commodi. Ea iure similique facilis id, quos at omnis minima totam nihil aperiam maiores! Aliquam voluptates modi doloremque assumenda architecto maiores sed delectus nisi, explicabo sit, adipisci repellat!
        </Container>
    </>);
};

export default About;
